/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIconUpdating: typeof import('./src/components/AppIconUpdating.vue')['default']
    AppSkeleton: typeof import('./src/components/AppSkeleton.vue')['default']
    CityDetails: typeof import('./src/components/CityDetails.vue')['default']
    CityList: typeof import('./src/components/CityList.vue')['default']
    CitySearch: typeof import('./src/components/CitySearch.vue')['default']
    IconClose: typeof import('./src/components/icon/IconClose.vue')['default']
    IconWeatherClearCloudy: typeof import('./src/components/icon/IconWeatherClearCloudy.vue')['default']
    IconWeatherCloudy: typeof import('./src/components/icon/IconWeatherCloudy.vue')['default']
    IconWeatherDrizzle: typeof import('./src/components/icon/IconWeatherDrizzle.vue')['default']
    IconWeatherError: typeof import('./src/components/icon/IconWeatherError.vue')['default']
    IconWeatherHail: typeof import('./src/components/icon/IconWeatherHail.vue')['default']
    IconWeatherIsolatedThunderstroms: typeof import('./src/components/icon/IconWeatherIsolatedThunderstroms.vue')['default']
    IconWeatherMostlyCloudy: typeof import('./src/components/icon/IconWeatherMostlyCloudy.vue')['default']
    IconWeatherPartlyCloudy: typeof import('./src/components/icon/IconWeatherPartlyCloudy.vue')['default']
    IconWeatherShowers: typeof import('./src/components/icon/IconWeatherShowers.vue')['default']
    IconWeatherSleet: typeof import('./src/components/icon/IconWeatherSleet.vue')['default']
    IconWeatherSnow: typeof import('./src/components/icon/IconWeatherSnow.vue')['default']
    IconWeatherSnowFlurries: typeof import('./src/components/icon/IconWeatherSnowFlurries.vue')['default']
    IconWeatherSunny: typeof import('./src/components/icon/IconWeatherSunny.vue')['default']
    IconWeatherThunderstroms: typeof import('./src/components/icon/IconWeatherThunderstroms.vue')['default']
    IconWeatherTornado: typeof import('./src/components/icon/IconWeatherTornado.vue')['default']
    IconWeatherWindy: typeof import('./src/components/icon/IconWeatherWindy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WeatherCardDay: typeof import('./src/components/weather/WeatherCardDay.vue')['default']
    WeatherCardDayError: typeof import('./src/components/weather/WeatherCardDayError.vue')['default']
    WeatherCardDayLoading: typeof import('./src/components/weather/WeatherCardDayLoading.vue')['default']
    WeatherCardHour: typeof import('./src/components/weather/WeatherCardHour.vue')['default']
    WeatherCardHourError: typeof import('./src/components/weather/WeatherCardHourError.vue')['default']
    WeatherCardHourLoading: typeof import('./src/components/weather/WeatherCardHourLoading.vue')['default']
    WeatherCardNow: typeof import('./src/components/weather/WeatherCardNow.vue')['default']
    WeatherCardNowError: typeof import('./src/components/weather/WeatherCardNowError.vue')['default']
    WeatherCardNowLoading: typeof import('./src/components/weather/WeatherCardNowLoading.vue')['default']
  }
}
